"""empty message

Revision ID: 7b2d7842773b
Revises: 
Create Date: 2022-07-18 20:57:27.741240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2d7842773b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('picture_profile_link', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_username'), 'User', ['username'], unique=True)
    op.create_table('Event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('begin_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('picture_cover', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Event_begin_date'), 'Event', ['begin_date'], unique=False)
    op.create_index(op.f('ix_Event_name'), 'Event', ['name'], unique=True)
    op.create_table('Token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=64), nullable=False),
    sa.Column('access_expiration', sa.DateTime(), nullable=False),
    sa.Column('refresh_token', sa.String(length=64), nullable=False),
    sa.Column('refresh_expiration', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Token_access_token'), 'Token', ['access_token'], unique=False)
    op.create_index(op.f('ix_Token_refresh_token'), 'Token', ['refresh_token'], unique=False)
    op.create_table('saved_events',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['Event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_events')
    op.drop_index(op.f('ix_Token_refresh_token'), table_name='Token')
    op.drop_index(op.f('ix_Token_access_token'), table_name='Token')
    op.drop_table('Token')
    op.drop_index(op.f('ix_Event_name'), table_name='Event')
    op.drop_index(op.f('ix_Event_begin_date'), table_name='Event')
    op.drop_table('Event')
    op.drop_index(op.f('ix_User_username'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
